### PR TITLE
2.0.0

### LINKED ISSUE #81: v2.0.0
I've started working on the next major for trilogy on the [next](https://github.com/citycide/trilogy/tree/next) branch. The goals of v2.0.0 are:

#### write in TypeScript

This is basically done but is probably always able to be improved, so PRs from other TypeScript users would definitely be appreciated. Flow definitions are **removed** and Flow is no longer officially supported. TypeScript's tooling is far better.

#### ~add plugin support~

~To keep the core of trilogy to a reasonable size we should implement a plugin system to allow new features. If you'd be interested in writing a trilogy plugin, please check out the progress at #82 and provide feedback.~

#### add lifecycle hooks

Plugins were implemented in early v2 prereleases but added far too much typing complexity and were not type safe. Many use cases of plugins could be achieved with more explicit hooks like `beforeCreate`, `afterUpdate`, etc.

#### improve usability

General API and usage improvements are also on the table and I'm open to proposals.

---

The [next](https://github.com/citycide/trilogy/tree/next) branch holds all the progress for this release, and betas are available on npm as `trilogy@next`.

### PR DESCRIPTION
**Pull request by citycide**
Closes #81 

> see #81 for a short writeup of the goals for v2.0.0

### tasks

* [x] write source in TypeScript
  * [x] remove rollup
  * [x] remove babel
* [x] use [`runtypes`](https://github.com/pelotom/runtypes) to check TS types at runtime
* [x] ~update~ remove flow definitions
* [x] throw more errors on unrecognized types or invalid values
* [x] update knex to close #73 (breaking change)
* [x] use generics for type information on models
  * `const games = await db.model<{ name: string }>('games', { name: String })`
* [x] various API improvements
  * [x] add synchronous `getModel` method (throws if model doesn't exist)
  * [x] make `update` and `remove` operations return an array of any modified or removed objects
  * [x] rename `incr` & `decr` to `increment` & `decrement`
    * `min` & `max` are ok as they're more commonly used abbreviations
  * [x] remove various overloads to reduce typing complexity
    * [x] `find` & `findOne` with column as first parameter (split to `findIn` & `findOneIn`)
    * [x] `count` with column as first parameter (split to `countIn`)
* [x] implement lifecycle hooks
  * [x] support canceling events from hook subscribers
* [x] update all documentation

### canceled items

* make `notNullable` the default for schemas
  * this had severe negative effects on usability
* add plugin system
  * dropped in favor of lifecycle hooks (see below)

### getting TypeScript compiler assistance on models

```ts
import { connect } from 'trilogy'
const db = connect(':memory:')

interface Game {
  name: string,
  players: number,
  is_card: boolean,
  is_dice: boolean
}

;(async () => {
  const games = await db.model<Game>('games', {
    name: String,
    players: Number,
    is_card: Boolean,
    is_dice: Boolean
  })

  await games.create({
    name: 'Solitaire',
    players: 1,
    is_card: true,
    is_dice: false
  })

  // type is inferred here as Game[]
  const allGames = await games.find()

  // you get suggestions and type checking here
  console.log(allGames[0].players)
  // -> 1
})()
```

### lifecycle hooks

I've decided to rip out the plugin support because it adds a lot of complexity around the type system, and it's really at odds with strict type checks. It's impossible to represent the nature of plugins/mixins well enough in TypeScript so plugins would inevitably be written in JavaScript so the author can avoid clawing their eyes out which therefore means the user loses type safety. I know this because while starting to write plugins I've been clawing my own eyes out and thinking I'd rather write it in JavaScript even if the user loses type safety.

To save many sets of eyeballs the plugin system of early v2 prereleases is going to be dropped and instead we'll have hooks. This is still yet to be finalized but the full set of hooks currently looks like this:

* `onQuery` &ndash; `(query: string) => any` (replacement for `TrilogyOptions.verbose`)
* `beforeCreate` &ndash; `(objectToBeCreated: D, options: CreateOptions) => any`
* `afterCreate` &ndash; `(createdObject: D, options: CreateOptions) => any`
* `beforeUpdate` &ndash; `(updateDelta: Partial<D>, criteria: Criteria<D>, options: UpdateOptions) => any`
* `afterUpdate` &ndash; `(itemsUpdated: D[], options: UpdateOptions) => any`
* `beforeRemove` &ndash; `(criteria: Criteria<D>, options: {}) => any`
* `afterRemove` &ndash; `(itemsRemoved: D[], options: {}) => any`

These would be much more explicit and type safe but still support many of the use cases for plugins. A few items to work out:

* ~What should the `beforeRemove` hook receive? The create hooks are clear because `create()` both accepts and returns a full object that can be passed to the hook. Update hooks should receive the data being modified (so hooks can further modify/prevent it). But `remove()` only accepts a criteria, so maybe that's all the hook gets?~

* ~`incr` & `decr` are relative atomic operations - we don't know the current value of the number being updated so we also don't know the new value until after we've already incremented. So what do we pass to the `beforeUpdate` hook in these scenarios? My current thought is an empty object for `data` but pass through `criteria`. This should allow most transformations that might be done in a `beforeUpdate` hook to work but essentially be no-ops. I don't think there are many use cases where you'd need to know the delta here anyway, so just having the `criteria` should be enough.~

* ~Should `clear()` trigger `{before,after}Remove` hooks?~

### CODE REVIEW

**Comment by citycide** [comment]
beta release is up under the `@next` tag for those who want to get a feel for it:

```shell
npm i trilogy@next
# or
npm i trilogy@2.0.0-beta.1
```

**Comment by citycide** [comment]
I'm running into some typing struggles due to the various forms that `criteria` can take for methods like `find()`. TS seems to always infer array instead of tuple, so it will always assume an argument like `['name', 'citycide']` or `['id', '>', 10]` is a list with multiple criteria.

While I like the current API it looks like it can't be easily typed, so I'm thinking about getting rid of some of the overload that knex allows. ie. `['name', 'citycide']` is the same as `{ name: 'citycide' }` anyway.

The 3-tuple form will be a little more complicated so I'm open to ideas on replacing it.

**Comment by citycide** [comment]
I _finally_ was able to type the existing signatures of all the functions taking a `Criteria`, thanks to TypeScript 2.8's [conditional types](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html). See d583f06a9864bf54bb73fdf76d5f3aa0e312720b for the implementation - it's pretty rad.

The trick is to differentiate between arrays & tuples, since TS always infers array and required explicit declaration or casting to get around that.

That pretty much leaves the plugin framework as the last box I want to check off for 2.0, so please if you have any feedback at all on its current state then comment or start a review.

**Comment by citycide** [comment]
I've been chipping at the plugin framework pretty steadily but there are several TS shortcomings that I think would make plugin development and usage in TS pretty much a nightmare. Vanilla JS dev & usage would probably be fine, but that kind of defeats the entire purpose of a strictly typed rewrite... [Objection.js](https://github.com/Vincit/objection.js) is in the same situation: all its plugins are written in JS because writing them in TS would be too painful.

I'm considering dropping the plugin support and instead adding a simpler hooks system or some kind of middleware, but I haven't worked up any alternatives yet.

**Comment by citycide** [comment]
It's been a bit so I'll give a quick status update - I'm still working on usability of the types & plugin architecture, which I think are both pretty solid. There are still some limitations with the type system in terms of handling functionality provided by multiple plugins but it seems unavoidable.

Sort of unrelated news - I've updated the closure list for this PR to remove all the Greenkeeper issues since I'm closing those early and disabling Greenkeeper (it's mostly unnecessary noise).

**Comment by ram-you** [comment]
npm i trilogy@next
 or
npm i trilogy@2.0.0-beta.2 (as beta.2 is the last)

**Comment by citycide** [comment]
This is blocked by a typescript compiler crash, see  https://github.com/Microsoft/TypeScript/issues/29884.

**Comment by citycide** [comment]
The typescript compiler crash is fixed and I've fixed a bunch of errors. I was _this close_ to just saying "ship it" when I find out that apparently the triggers I implemented to approximate "returning" clauses don't work in `sql.js`, only in native... I'm going to see if they work on `sql.js@1.x` but may need to file an issue over there.

**Comment by citycide** [comment]
`2.0.0-rc.4` has been released and is very likely to be the last release candidate. It's been a long time coming and I think v2 is imminent! ✊

Please share any feedback if you have any!

**Pull request merged**
